version: '2'

services:
  nginx:
    image: localhost:5000/nginx_my:1.21
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1
    ports:
      - 8085:8085
    volumes:
      - ./index:/usr/share/nginx/html
    networks:
      nginx_net:
        ipv4_address: 192.168.80.3

  httpd:
    image: localhost:5000/httpd_my:2.4
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1
    ports:
      - 8090:8090
    volumes:
      - ./index:/usr/local/apache2/htdocs
    networks:
      httpd_net:
        ipv4_address: 192.168.80.131

networks:
  nginx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/25
          gateway: 192.168.80.1
  httpd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.128/25
          gateway: 192.168.80.129
